### ISSUE TITLE
java.lang.zip.ZipException: No entries error while converting Minecraft

### ISSUE THREAD

**Issue by zhuowei** [zhuowei/Boardwalk#1]
Version of Boardwalk: 1.0

Version of Android: 4.2

Device model: Asus MeMoPad HD 7, Lenovo A3000

Description of the problem:

"java.lang.zip.ZipException: No entries error while converting Minecraft" displays in runRename.

https://twitter.com/egyptiansanta/status/521516515418333184

https://twitter.com/joshuaplaysmcpe/status/521530493309698049

Thanks to @egyptiansanta and @joshuaplaysmcpe for reporting this.

**Comment by dethdp** [comment]
I can't play

**Comment by embett** [comment]
No play game

**Comment by henrique2000** [comment]
Version of Boardwalk: 1.1

Version of android: 4.2.2

Device model: BLU BLU DASH 5.0

Description of the problem:

"java.lang.zip.ZipException: Dex returned 11

**Comment by henrique2000** [comment]
Version of Boardwalk: 1.1

Version of android: 4.2.2

Device model: BLU BLU DASH 5.0

Description of the problem:

"java.lang.zip.ZipException: Dex returned 11 with error:
