### ISSUE TITLE
too awsome but....

### ISSUE THREAD

**Issue by rattata2me** [zhuowei/Boardwalk#101]
zhuowei i like all your works and for me this is your best creation but i like to play minecraft with mouse. Can you do a toggle button or something like this to put on mouse controlling in game ? I am using mouse keyboard 2 touch but it doesn't work properly so can you make a fine input of the mouse in minecraft like the keyboard input ?

**Comment by EnderBrine101** [comment]
This would be really awesome to add mouse and keyboard support.
