### ISSUE TITLE
boardwalk 1.0.7 crash with mc1.8

### ISSUE THREAD

**Issue by whdgmawkd** [zhuowei/Boardwalk#116]
Version of Boardwalk: 1.0.7

Version of Android: 5.0.2 (cm12)

Device model: lg g2 (f320)

Description of the problem:

E/AndroidRuntime(21799): FATAL EXCEPTION: main
E/AndroidRuntime(21799): Process: net.zhuoweizhang.boardwalk, PID: 21799
E/AndroidRuntime(21799): java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/net.zhuoweizhang.boardwalk-1/base.apk"],nativeLibraryDirectories=[/data/app/net.zhuoweizhang.boardwalk-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libglshim.so"
E/AndroidRuntime(21799): 	at java.lang.Runtime.loadLibrary(Runtime.java:366)
E/AndroidRuntime(21799): 	at java.lang.System.loadLibrary(System.java:989)
E/AndroidRuntime(21799): 	at net.zhuoweizhang.boardwalk.MainActivity.onCreate(MainActivity.java:106)
E/AndroidRuntime(21799): 	at android.app.Activity.performCreate(Activity.java:5933)
E/AndroidRuntime(21799): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
E/AndroidRuntime(21799): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2267)
E/AndroidRuntime(21799): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2393)
E/AndroidRuntime(21799): 	at android.app.ActivityThread.access$800(ActivityThread.java:147)
E/AndroidRuntime(21799): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1281)
E/AndroidRuntime(21799): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(21799): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(21799): 	at android.app.ActivityThread.main(ActivityThread.java:5258)
E/AndroidRuntime(21799): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(21799): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(21799): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
E/AndroidRuntime(21799): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
W/ActivityManager(  808):   Force finishing activity net.zhuoweizhang.boardwalk/.MainActivity
W/ActivityManager(  808):   Force finishing activity net.zhuoweizhang.boardwalk/.LauncherActivity

**Comment by zhuowei** [comment]
http://zhuoweizhang.net/Boardwalk/Boardwalk-release.apk
