### ISSUE TITLE
crafting problem

### ISSUE THREAD

**Issue by Savage80HD** [zhuowei/Boardwalk#118]
Version of Boardwalk: 1.0.6

Version of Android: 5.0.1

Device model: Nvidia Shield Tablet

Description of the problem: when crafting I can't separate items from a stack, I've tried everything, even using my wireless mouse. If I want to make a pickaxe I have to drop a piece of cobble on the ground, keep the stack hovering with my "curser" or in the crafting area until the item is picked back up so that it will occupy its own inventory space, then put that single (or however many I drop) piece of cobble into the crafting area, then repeat. Crafting chests, furnaces, and solid blocks (gold, iron, coal, etc) is very frustrating not sure if it's device specific, or if you're aware, but all that being said, this is an amazing thing you've done, I'm very impressed, I thought it would be years before I had a vanilla, mobile, Minecraft with redstone, let alone the more complex stuff 😊 thank you for your hard work and offering it for free, do you have a service to accept donations?

**Comment by harys99** [comment]
Yeah, it's the she for me. I think it's a bug, so you're not the only one :)

**Comment by harys99** [comment]
It's the same, I mean. Damn you, autocorrect! :D

**Comment by zhuowei** [comment]
Fixed in latest beta: http://zhuoweizhang.net/Boardwalk/Boardwalk-release.apk hold Sec to right click
