### ISSUE TITLE
Boardwalk beta 1.1 crashes on launch

### ISSUE THREAD

**Issue by Dinosandwich123** [zhuowei/Boardwalk#126]
Version of Boardwalk: Beta 1.1

Version of Android: 4.3

Device model: Samsung Galaxy Tab 4

Description of the problem: Whenever I try to load a Minecraft version by clicking launch, boardwalk will load the game for 1 second and then crash. This happens when running every version of Minecraft, and only  crashes on the beta releases, not the google play version. Unfortunately there is no crash log.

**Comment by Docmine7** [comment]
I got the same error

**Comment by zhuowei** [comment]
Try http://zhuoweizhang.net/Boardwalk/Boardwalk-release.apk, which should fix this.
The multiplayer fix crashes on Android versions below 4.4.4; I test on 5.0 only so didn't catch this.
