### ISSUE TITLE
Getting error in 1.07 - 1.1 b1

### ISSUE THREAD

**Issue by oDeathwingo** [zhuowei/Boardwalk#127]
Version of Boardwalk: 1.1 b1

Version of Android: 4.4.2

Device model:Lenovo Yoga tablet 

Description of the problem:Well i can run up to 1.06 but 1.07 and above gives an instant crash with the following text "boardwalk stopped working" .

**Comment by Dinosandwich123** [comment]
A lot of people are having this bug, me included. I think its something Zhuowei should look into.

**Comment by zhuowei** [comment]
Try latest beta? 1.0.7 is completely broken (it was missing a file); 1.1 betas was broken on 4.4.2 and below. The released 1.1 fixes these problems.
