### ISSUE TITLE
Multiplayer crashes

### ISSUE THREAD

**Issue by ComputeLinux** [zhuowei/Boardwalk#155]
Version of Boardwalk: Latest Beta
Your device model: N7 2013
Version of Android you're running: LPX13D dev preview (rooted)
A description of the error: MP crashes MC, or times out instantly after joining

**Comment by EnderBrine101** [comment]
This could be a server, internetr ot client problem. Try checking you have good internet and sometimes it can be the servers fsult. Also i recommend plsying on strong WIFI connection, even on PC.

**Comment by ComputeLinux** [comment]
Fixed by self on #173
