### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by Nathanbdb2000** [zhuowei/Boardwalk#164]
Hello guys, I just send you a E-Mail for some questions... I very liked how you make a real minecraft for Android. But i just have a question... How this is possible? If you can with minecraft, does it possible with an other game, like The Elder Scrolls : oblivion? because on my nvidia shield I play Boardwalk at 20 fps. I really think that other game can be play at 50-60 fps. Can you just respond my E-Mail with all the answer please?

A big tanks, nice work :+1:

**Comment by zhuowei** [comment]
Minecraft is in Java, which Android supports, and someone already wrote a compatibility layer for OpenGL (the graphics layer it uses) to OpenGL ES (what Android supports), so this was relatively easy.

Oblivion is compiled to native x86 code; translating that to the ARM processor used on the Shield would be difficult. (It's possible: Intel does the reverse (ARM to x86) for their Atom tablets, but unfortunately I'm not Intel and don't have a gazillion dollars)

**Comment by zhuowei** [comment]
If you want a device that can play Oblivion, try getting one of the cheap Windows tablets, such as the Stream 7 - they run full Windows and might run games at an acceptable speed.

**Comment by Nathanbdb2000** [comment]
You very help me, thanks fort the information, I will try and and let you news...

Le 4 avr. 2015 01:23, zhuowei <notifications@github.com> a écrit :
If you want a device that can play Oblivion, try getting one of the cheap Windows tablets, such as the Stream 7 - they run full Windows and might run games at an acceptable speed.

---
