### ISSUE TITLE
1.8 Crashes on Multiplayer

### ISSUE THREAD

**Issue by testinstien** [zhuowei/Boardwalk#173]
Version of Boardwalk: 1.1

Version of Android: 5.0.1

Device model: SHIELD Tablet

Description of the problem: When I got into 1.8 and try to go online I just crash. It goes like 2 frames then "Boardwalk is not responding" I can't join servers in 1.8 without crashes (help)

**Comment by ComputeLinux** [comment]
This seems to be an issue with versions > KitKat but <5.0.2. 5.0.2 fixed this for me.

**Comment by EnderBrine101** [comment]
Duplicate of #155

**Comment by fallout987** [comment]
EnderBrine I'm new to github so I honestly don't know anything and it just doesn't work for me.

**Comment by EnderBrine101** [comment]
@ComputeLinex how can YOU reference issues?

**Comment by EnderBrine101** [comment]
@ComputeLinux

**Comment by EnderBrine101** [comment]
Wait nvm got it

**Comment by EnderBrine101** [comment]
@fallout987 Try and play 1.7 servers. 1.8 is confirmed to have lag issues by mojang. Also, is your device Dalvik or ART? (The runtime)

**Comment by EnderBrine101** [comment]
ART runtime works best with boardwalk - but Dalvik is not reccomended for 1.8 - so play 1.7 for now ;)

**Comment by fallout987** [comment]
You cant see on android 5 not in options or dev options

**Comment by arngrg** [comment]
Android 5.0 is running on art at all time on all devices.

**Comment by fallout987** [comment]
@arngrg What about the Nvidia shield?

**Comment by fallout987** [comment]
Okay... so why does 1.8 not work for me?

**Comment by arngrg** [comment]
Nobody can play 1.8 multiplayer.

**Comment by fallout987** [comment]
Ok

**Comment by ComputeLinux** [comment]
not true, mine works fine.

**Comment by ComputeLinux** [comment]
you need 1.8.3 or higher though

**Comment by arngrg** [comment]
how? I cant play ONLINE.

**Comment by arngrg** [comment]
What server do you play and how much fps?

**Comment by fallout987** [comment]
I use 1.8.3

**Comment by KStormTheOne** [comment]
Oh is language files appearing for you and check resource packs for 1.8 and see of it says missing pack.mcmeta

**Comment by KStormTheOne** [comment]
Also can you hear sound, I cannot

**Comment by fallout987** [comment]
I can hear sound and yeah could be my texture pack cause I use a 8x8 or 16x16 so I get better FPS

**Comment by KStormTheOne** [comment]
Do your languages show up

**Comment by spideyroc1** [comment]
I have no pack.Mcmeta how do I get it

**Comment by bullfrogberry** [comment]
So one person can play 1.8 multiplayer.  I am using 1.8.8 (1.7.10 works fine) is there a work around to play 1.8 online? Mine also freezes after only a Frame or two.

**Comment by s12227054** [comment]
No one can play multiplayer

**Comment by testinstien** [comment]
Thank you for replying to a few year old post.
