### ISSUE TITLE
I have some problems with boardwalk

### ISSUE THREAD

**Issue by arngrg** [zhuowei/Boardwalk#175]
Version of Boardwalk: 1.1

Version of Android: Android 5.0.2

Device model: Galaxy tab s/sm-t800

Description of the problem: As you can see at the title i have problem with boardwalk. It gives error when i try to download. I tryed all versions but it wont download. My device is sm t800/galaxy tab s with android 5.0.2. I want on android 5.0 because it runs on art mode.
NOTE: it works on android 4.4.2 but it dont work on 5.0.2.

Another problem: i want to join multiplayer on 1.8. I have premium. But when i try it joins server then it stops boardwalk. Thank you.                      EDIT: I have tryed to join servers on 4.4.2.
Picture of problem 1: 
![studio_20150419_124341](https://cloud.githubusercontent.com/assets/12032982/7229677/2a96c492-e76f-11e4-9ad7-6d45326a62cc.png)

**Comment by arngrg** [comment]
Somebody please help me!!!!!

**Comment by joho506** [comment]
Try deleting the boardwalk folder on your SD card, then downloading 1.7.
Also search for 'dex returned 6' on this issue tracker.

**Comment by arngrg** [comment]
1. I dont have sd card.
2. Tryed to format and dont work.
3. Can we play minecraft 1.8 multiplayer?

Thank you again

**Comment by arngrg** [comment]
4. If it need, my device is rooted too.

**Comment by joho506** [comment]
I mean with an app like Cabinet or ES (
https://play.google.com/store/apps/details?id=com.afollestad.cabinet),
delete the boardwalk folder on the SD card/device storage.
1.8 isn't particularly stable yet, but by all means try it.

**Comment by arngrg** [comment]
I deleted with zarchiver and tryed again now but it wont download.

**Comment by arngrg** [comment]
Tryed with cabinet and dont work but thank you much

**Comment by arngrg** [comment]
Cannanybody help me? I want to play much.

**Comment by henrique2000** [comment]
Version of Boardwalk: 1.1

Version of android: 4.2.2

Device model: BLU BLU DASH 5.0

Description of the problem:

"java.lang.zip.ZipException: Dex returned 11 with error

**Comment by arngrg** [comment]
Henrique you cant play because your ram is much little for minecraft.

**Comment by arngrg** [comment]
And I understand now why its not working. Android 5.0 uses much ram. Closing

**Comment by jbdman** [comment]
Thats not why, i have 5.0 on my kindle fire hd (512mb ram) and it runs fine. But on my galaxy s5 it dont.  This is samsungs shit software.

**Comment by arngrg** [comment]
Samsung is shit. It works on 4.4.2 but it wont work on 5.0 on galaxy tab s. But how do you play with fire? I think u get like 1 fps xD

**Comment by jbdman** [comment]
I installed Cyanogen Mod 12 and get like 10-15fps (lol like my old pc)

**Comment by arngrg** [comment]
Omg! Why do you dont try to install cynogenmod 12 to s5? It should work.

**Comment by jbdman** [comment]
i have the att locked bootloader. :(

**Comment by FanOfZhouwei** [comment]
How much ram do I need to work sorry for the grammar if its wrong because I'm a Filipino thanks :)

**Comment by FranzYLO** [comment]
It's not working because the .downloaded file can open because I didn't download if it works for someone it would be cool to have a working Boardwalk  folder Download it would probably work with it
