### ISSUE TITLE
Github problem

### ISSUE THREAD

**Issue by ComputeLinux** [zhuowei/Boardwalk#178]
Version of Boardwalk: Github issue tracker

Version of Android: People (v.I.T.S.O.V.E.R.9.0.0.0.!)

Device model: Brain (Model WTFEngine)

Description of the problem: People are reporting Dex returned 11 over and over again. Read the damn FAQ, I put it there for a reason.

**Comment by ComputeLinux** [comment]
Applies to #177 #171 #174 #175 #158 #150 #148 #147 #137 #133 #131 #124 #115 #114 #92 #59 #48  #31 #25

**Comment by joho506** [comment]
However, spamming everyone who's watching the repo *even more* is not particularly good etiquette.

**Comment by seth828** [comment]
Really damn professional of you to act like a jerk! Grow up!

**Comment by spilortek** [comment]
For me it's dex deturned 6 with error, not 11

**Comment by ComputeLinux** [comment]
closing
