### ISSUE TITLE
Cannot open any worlds

### ISSUE THREAD

**Issue by kristomayo** [zhuowei/Boardwalk#205]
Monday, July 13, 2015
Boardwalk Version 1.1
Samsung Galaxy Tab 4 7.0 (SM-T230NU)
Android 4.4.2
No screenshot available, as it doesn't have anything.

When I try to open or create a world, Minecraft seems to "crash", even though it doesn't have a crash report. The saves aren't corrupt (at least I don't think they are) because I just tried to create a world and it crashed. Also, the saves worked the last time I opened them up! What could this be? Is anything corrupted? Do I need to delete anything? I don't want to restart with my saves because I worked so hard to start them! Help! (ASAP?)

**Comment by kristomayo** [comment]
NVM, the game works now! :D

**Comment by theblueslimegameing** [comment]
I can't play it because I don't have a PC can I make a account from
boardwalk?
