### ISSUE TITLE
Dex returned 6 with error

### ISSUE THREAD

**Issue by DavidDomkar** [zhuowei/Boardwalk#206]
Version of Boardwalk: 1.1

Version of Android: 5.1.1

Device model: asus Nexus 7 2012

Description of the problem: When I click play it says "Error: java.lang.RuntimeException: java.lang.RuntimeException: Dex returned 6 with error" in previous version it works fine.

**Comment by jbdman** [comment]
Same on a Galaxy S5, what do you mean previous versions, of boardwalk or android?

**Comment by AmbroseDoesMC** [comment]
Dude same 
![screenshot_2015-08-24-23-32-42](https://cloud.githubusercontent.com/assets/13937753/9432407/a8d66d76-49df-11e5-889d-f77e1db1f801.png)

**Comment by AmbroseDoesMC** [comment]
Pz fix

**Comment by AmbroseDoesMC** [comment]
I will give it 5 stars if fixed

**Comment by DEXIT33** [comment]
I meant previous version of broadwalk
