### ISSUE TITLE
Non-premium

### ISSUE THREAD

**Issue by Megaeloelo** [zhuowei/Boardwalk#283]
Please make it non-premium or offline.
Ps: Minecraft non-premium isn't a piracy ,
Sorry for bad english.

**Comment by Megaeloelo** [comment]
Ok I changed some things in Yggdrassil authentification file and I can now log as non-premium.
Closing.

**Comment by Stefan34** [comment]
Pls show me how?

**Comment by Megaeloelo** [comment]
I can't without permissions of developer .

**Comment by Stefan34** [comment]
Pls bro I am begging you to show me the file

**Comment by Stefan34** [comment]
Pls bro msg me the apk file pls

**Comment by Stefan34** [comment]
.class public Lnet/zhuoweizhang/boardwalk/yggdrasil/YggdrasilAuthenticator;
.super Ljava/lang/Object;
.source "YggdrasilAuthenticator.java"

# static fields
.field private static final API_URL:Ljava/lang/String; = "
https://authserver.mojang.com"

# instance fields
.field private clientName:Ljava/lang/String;

.field private clientVersion:I

.field private gson:Lcom/google/gson/Gson;

# direct methods
.method public constructor <init>()V
    .registers 2

    .prologue
    .line 11
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    .line 16
    const-string v0, "Minecraft"

    iput-object v0, p0,
Lnet/zhuoweizhang/boardwalk/yggdrasil/YggdrasilAuthenticator;->clientName:Ljava/lang/String;

    .line 17
    const/4 v0, 0x1

    iput v0, p0,
Lnet/zhuoweizhang/boardwalk/yggdrasil/YggdrasilAuthenticator;->clientVersion:I

    .line 18
    new-instance v0, Lcom/google/gson/Gson;

    invoke-direct {v0}, Lcom/google/gson/Gson;-><init>()V

    iput-object v0, p0,
Lnet/zhuoweizhang/boardwalk/yggdrasil/YggdrasilAuthenticator;->gson:Lcom/google/gson/Gson;

    return-void
.end method

.method private
makeRequest(Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Class;)Ljava/lang/Object;
    .registers 19
    .param p1, "endpoint"    # Ljava/lang/String;
    .param p2, "inputObject"    # Ljava/lang/Object;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "<T:",
            "Ljava/lang/Object;",
            ">(",
            "Ljava/lang/String;",
            "Ljava/lang/Object;",
            "Ljava/lang/Class",
            "<TT;>;)TT;"
        }
    .end annotation

    .annotation system Ldalvik/annotation/Throws;
        value = {
            Ljava/io/IOException;
        }
    .end annotation

    .prologue
    .line 21
    .local p3, "responseClass":Ljava/lang/Class;, "Ljava/lang/Class<TT;>;"
    const/4 v4, 0x0

    .line 23
    .local v4, "is":Ljava/io/InputStream;
    const/16 v12, 0x4000

    new-array v2, v12, [B

    .line 24
    .local v2, "buf":[B
    const/4 v9, -0x1

    .line 25
    .local v9, "statusCode":I
    new-instance v1, Ljava/io/ByteArrayOutputStream;

    invoke-direct {v1}, Ljava/io/ByteArrayOutputStream;-><init>()V

    .line 26
    .local v1, "bos":Ljava/io/ByteArrayOutputStream;
    iget-object v12, p0,
Lnet/zhuoweizhang/boardwalk/yggdrasil/YggdrasilAuthenticator;->gson:Lcom/google/gson/Gson;

    move-object/from16 v0, p2

    invoke-virtual {v12, v0},
Lcom/google/gson/Gson;->toJson(Ljava/lang/Object;)Ljava/lang/String;

    move-result-object v8

    .line 27
    .local v8, "requestJson":Ljava/lang/String;
    const/4 v10, 0x0

    .line 30
    .local v10, "url":Ljava/net/URL;
    :try_start_14
    new-instance v11, Ljava/net/URL;

    new-instance v12, Ljava/lang/StringBuilder;

    invoke-direct {v12}, Ljava/lang/StringBuilder;-><init>()V

    const-string v13, "https://authserver.mojang.com/"

    invoke-virtual {v12, v13},
Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v12

    move-object/from16 v0, p1

    invoke-virtual {v12, v0},
Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v12

    invoke-virtual {v12},
Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v12

    invoke-direct {v11, v12}, Ljava/net/URL;-><init>(Ljava/lang/String;)V
    :try_end_2e
    .catchall {:try_start_14 .. :try_end_2e} :catchall_c8

    .line 31
    .end local v10    # "url":Ljava/net/URL;
    .local v11, "url":Ljava/net/URL;
    :try_start_2e
    invoke-virtual {v11},
Ljava/net/URL;->openConnection()Ljava/net/URLConnection;

    move-result-object v3

    check-cast v3, Ljava/net/HttpURLConnection;

    .line 32
    .local v3, "conn":Ljava/net/HttpURLConnection;
    const-string v12, "User-Agent"

    const-string v13, "Boardwalk"

    invoke-virtual {v3, v12, v13},
Ljava/net/HttpURLConnection;->setRequestProperty(Ljava/lang/String;Ljava/lang/String;)V

    .line 33
    const/4 v12, 0x1

    invoke-virtual {v3, v12}, Ljava/net/HttpURLConnection;->setDoInput(Z)V

    .line 34
    const-string v12, "POST"

    invoke-virtual {v3, v12},
Ljava/net/HttpURLConnection;->setRequestMethod(Ljava/lang/String;)V

    .line 35
    const-string v12, "Content-Type"

    const-string v13, "application/json"

    invoke-virtual {v3, v12, v13},
Ljava/net/HttpURLConnection;->setRequestProperty(Ljava/lang/String;Ljava/lang/String;)V

    .line 36
    invoke-virtual {v3}, Ljava/net/HttpURLConnection;->connect()V
    :try_end_4e
    .catchall {:try_start_2e .. :try_end_4e} :catchall_ae

    .line 37
    const/4 v5, 0x0

    .line 39
    .local v5, "os":Ljava/io/OutputStream;
    :try_start_4f
    invoke-virtual {v3},
Ljava/net/HttpURLConnection;->getOutputStream()Ljava/io/OutputStream;

    move-result-object v5

    .line 40
    sget-object v12,
Lnet/zhuoweizhang/boardwalk/downloader/DownloadUtils;->utf8:Ljava/nio/charset/Charset;

    invoke-virtual {v8, v12},
Ljava/lang/String;->getBytes(Ljava/nio/charset/Charset;)[B

    move-result-object v12

    invoke-virtual {v5, v12}, Ljava/io/OutputStream;->write([B)V
    :try_end_5c
    .catchall {:try_start_4f .. :try_end_5c} :catchall_a7

    .line 42
    if-eqz v5, :cond_61

    :try_start_5e
    invoke-virtual {v5}, Ljava/io/OutputStream;->close()V

    .line 44
    :cond_61
    invoke-virtual {v3}, Ljava/net/HttpURLConnection;->getResponseCode()I

    move-result v9

    .line 45
    const/16 v12, 0xc8

    if-eq v9, v12, :cond_b6

    .line 46
    invoke-virtual {v3},
Ljava/net/HttpURLConnection;->getErrorStream()Ljava/io/InputStream;

    move-result-object v4

    .line 51
    :goto_6d
    invoke-static {v4, v1, v2},
Lnet/zhuoweizhang/boardwalk/util/IoUtil;->pipe(Ljava/io/InputStream;Ljava/io/OutputStream;[B)V
    :try_end_70
    .catchall {:try_start_5e .. :try_end_70} :catchall_ae

    .line 53
    if-eqz v4, :cond_75

    .line 55
    :try_start_72
    invoke-virtual {v4}, Ljava/io/InputStream;->close()V
    :try_end_75
    .catch Ljava/lang/Exception; {:try_start_72 .. :try_end_75} :catch_c4

    .line 61
    :cond_75
    :goto_75
    new-instance v7, Ljava/lang/String;

    invoke-virtual {v1}, Ljava/io/ByteArrayOutputStream;->toByteArray()[B

    move-result-object v12

    sget-object v13,
Lnet/zhuoweizhang/boardwalk/downloader/DownloadUtils;->utf8:Ljava/nio/charset/Charset;

    invoke-direct {v7, v12, v13},
Ljava/lang/String;-><init>([BLjava/nio/charset/Charset;)V

    .line 63
    .local v7, "outString":Ljava/lang/String;
    const/16 v12, 0xc8

    if-eq v9, v12, :cond_bb

    .line 64
    new-instance v12, Ljava/lang/RuntimeException;

    new-instance v13, Ljava/lang/StringBuilder;

    invoke-direct {v13}, Ljava/lang/StringBuilder;-><init>()V

    const-string v14, "Status: "

    invoke-virtual {v13, v14},
Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v13

    invoke-virtual {v13, v9},
Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;

    move-result-object v13

    const-string v14, ":"

    invoke-virtual {v13, v14},
Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v13

    invoke-virtual {v13, v7},
Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v13

    invoke-virtual {v13},
Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v13

    invoke-direct {v12, v13},
Ljava/lang/RuntimeException;-><init>(Ljava/lang/String;)V

    throw v12

    .line 42
    .end local v7    # "outString":Ljava/lang/String;
    :catchall_a7
    move-exception v12

    if-eqz v5, :cond_ad

    :try_start_aa
    invoke-virtual {v5}, Ljava/io/OutputStream;->close()V

    :cond_ad
    throw v12
    :try_end_ae
    .catchall {:try_start_aa .. :try_end_ae} :catchall_ae

    .line 53
    .end local v3    # "conn":Ljava/net/HttpURLConnection;
    .end local v5    # "os":Ljava/io/OutputStream;
    :catchall_ae
    move-exception v12

    move-object v10, v11

    .end local v11    # "url":Ljava/net/URL;
    .restart local v10    # "url":Ljava/net/URL;
    :goto_b0
    if-eqz v4, :cond_b5

    .line 55
    :try_start_b2
    invoke-virtual {v4}, Ljava/io/InputStream;->close()V
    :try_end_b5
    .catch Ljava/lang/Exception; {:try_start_b2 .. :try_end_b5} :catch_c6

    .line 57
    :cond_b5
    :goto_b5
    throw v12

    .line 48
    .end local v10    # "url":Ljava/net/URL;
    .restart local v3    # "conn":Ljava/net/HttpURLConnection;
    .restart local v5    # "os":Ljava/io/OutputStream;
    .restart local v11    # "url":Ljava/net/URL;
    :cond_b6
    :try_start_b6
    invoke-virtual {v3},
Ljava/net/HttpURLConnection;->getInputStream()Ljava/io/InputStream;
    :try_end_b9
    .catchall {:try_start_b6 .. :try_end_b9} :catchall_ae

    move-result-object v4

    goto :goto_6d

    .line 66
    .restart local v7    # "outString":Ljava/lang/String;
    :cond_bb
    iget-object v12, p0,
Lnet/zhuoweizhang/boardwalk/yggdrasil/YggdrasilAuthenticator;->gson:Lcom/google/gson/Gson;

    move-object/from16 v0, p3

    invoke-virtual {v12, v7, v0},
Lcom/google/gson/Gson;->fromJson(Ljava/lang/String;Ljava/lang/Class;)Ljava/lang/Object;

    move-result-object v6

    .line 67
    .local v6, "outResult":Ljava/lang/Object;, "TT;"
    return-object v6

    .line 56
    .end local v6    # "outResult":Ljava/lang/Object;, "TT;"
    .end local v7    # "outString":Ljava/lang/String;
    :catch_c4
    move-exception v12

    goto :goto_75

    .end local v3    # "conn":Ljava/net/HttpURLConnection;
    .end local v5    # "os":Ljava/io/OutputStream;
    .end local v11    # "url":Ljava/net/URL;
    .restart local v10    # "url":Ljava/net/URL;
    :catch_c6
    move-exception v13

    goto :goto_b5

    .line 53
    :catchall_c8
    move-exception v12

    goto :goto_b0
.end method

# virtual methods
.method public
authenticate(Ljava/lang/String;Ljava/lang/String;Ljava/util/UUID;)Lnet/zhuoweizhang/boardwalk/yggdrasil/AuthenticateResponse;
    .registers 10
    .param p1, "username"    # Ljava/lang/String;
    .param p2, "password"    # Ljava/lang/String;
    .param p3, "clientId"    # Ljava/util/UUID;
    .annotation system Ldalvik/annotation/Throws;
        value = {
            Ljava/io/IOException;
        }
    .end annotation

    .prologue
    .line 72
    new-instance v0,
Lnet/zhuoweizhang/boardwalk/yggdrasil/AuthenticateRequest;

    iget-object v4, p0,
Lnet/zhuoweizhang/boardwalk/yggdrasil/YggdrasilAuthenticator;->clientName:Ljava/lang/String;

    iget v5, p0,
Lnet/zhuoweizhang/boardwalk/yggdrasil/YggdrasilAuthenticator;->clientVersion:I

    move-object v1, p1

    move-object v2, p2

    move-object v3, p3

    invoke-direct/range {v0 .. v5},
Lnet/zhuoweizhang/boardwalk/yggdrasil/AuthenticateRequest;-><init>(Ljava/lang/String;Ljava/lang/String;Ljava/util/UUID;Ljava/lang/String;I)V

    .line 73
    .local v0,
"request":Lnet/zhuoweizhang/boardwalk/yggdrasil/AuthenticateRequest;
    const-string v1, "authenticate"

    const-class v2,
Lnet/zhuoweizhang/boardwalk/yggdrasil/AuthenticateResponse;

    invoke-direct {p0, v1, v0, v2},
Lnet/zhuoweizhang/boardwalk/yggdrasil/YggdrasilAuthenticator;->makeRequest(Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Class;)Ljava/lang/Object;

    move-result-object v1

    check-cast v1,
Lnet/zhuoweizhang/boardwalk/yggdrasil/AuthenticateResponse;

    return-object v1
.end method

.method public
refresh(Ljava/lang/String;Ljava/util/UUID;)Lnet/zhuoweizhang/boardwalk/yggdrasil/RefreshResponse;
    .registers 6
    .param p1, "authToken"    # Ljava/lang/String;
    .param p2, "clientId"    # Ljava/util/UUID;
    .annotation system Ldalvik/annotation/Throws;
        value = {
            Ljava/io/IOException;
        }
    .end annotation

    .prologue
    .line 77
    new-instance v0, Lnet/zhuoweizhang/boardwalk/yggdrasil/RefreshRequest;

    invoke-direct {v0, p1, p2},
Lnet/zhuoweizhang/boardwalk/yggdrasil/RefreshRequest;-><init>(Ljava/lang/String;Ljava/util/UUID;)V

    .line 78
    .local v0,
"request":Lnet/zhuoweizhang/boardwalk/yggdrasil/RefreshRequest;
    const-string v1, "refresh"

    const-class v2, Lnet/zhuoweizhang/boardwalk/yggdrasil/RefreshResponse;

    invoke-direct {p0, v1, v0, v2},
Lnet/zhuoweizhang/boardwalk/yggdrasil/YggdrasilAuthenticator;->makeRequest(Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Class;)Ljava/lang/Object;

    move-result-object v1

    check-cast v1, Lnet/zhuoweizhang/boardwalk/yggdrasil/RefreshResponse;

    return-object v1
.end method


WHAT TO CHANGE?
