### ISSUE TITLE
Minecraft can't launch(crash) after version 1.1

### ISSUE THREAD

**Issue by Kenny-Hui** [zhuowei/Boardwalk#310]
It Seems that BoardWalk will crash on the version that is greater then 1.1,I tested 1.2,1.3 and1.4,all not working,however only 1.9 can go to title screen,but when loaded the world,it crashed and back to boardwalk screen,only Minecraft 1.0 and 1.1 is working
Phone Spec:
Model:LG-D802(LG G2)
Android version:Android 5.0.1

**Comment by RyanGamingXbox** [comment]
Also, me! My specs are SM-J12016. Its a damn good phone! This product is also abandoned. Since it hasen't been updated for a year or so.
