### ISSUE TITLE
Boardwalk wont install minecraft fully

### ISSUE THREAD

**Issue by leem919** [zhuowei/Boardwalk#312]
Version of Boardwalk
1.1

Your device model
SM-G930V

Version of Android you're running
7.0

A description of the error
installs fine until it gets to "converting it.unimi.dsi:fastutil:7.1.0" then it just gets stuck on that stage

(Optionally) a screenshot of the error
http://i.imgur.com/HAWSzrY.png

**Comment by leem919** [comment]
FYI, I updated to version 1.2 and the issue still persists.

**Comment by chrisisonwildcode** [comment]
Same issue with Google pixel 2 XL, android 8.1.0, and Boardwalk 1.2

**Comment by Seravilo** [comment]
I'm having the same problem, but my details are:

Boardwalk 1.2

Sony Xperia 2 model H3113

Android version 8.0.0 (Oreo)

Everything works fine, but always get stuck "converting it.unimi.dsi:fastutil:7.1.0"

Screenshot: https://www.dropbox.com/s/35l13i21x756c76/_20180617_223735.JPG?dl=0
