### ISSUE TITLE
Dex returned 2 with error

### ISSUE THREAD

**Issue by Levyks** [zhuowei/Boardwalk#324]
Version of Boardwalk:the latest(Boardwalk-release.apk), but i tested 1.1 and 1.2

Version of Android:7.1.2

Device model:Xiaomi Redmi 4X(3GB ram) 

Description of the problem:don't launch, something of memory, but i have 3gb 

![screenshot_2018-02-18-14-46-21-617_net zhuoweizhang boardwalk](https://user-images.githubusercontent.com/16294244/36355029-7c00e318-14bb-11e8-9d0c-af12f2110932.png)

**Comment by InvalidSudo** [comment]
Boardwalk has been removed from the play store because it doesn't work with Android 7 and 8, according to what the developer of this app said. Stay tuned.
