### ISSUE TITLE
Request Source Code Release

### ISSUE THREAD

**Issue by ZafotheNinja** [zhuowei/Boardwalk#326]
This git has a huge collection of bugs that need to be squashed and no updates in over 3 years. Is it safe to say that you haven't had time and to release this app as open source?

**Comment by zhuowei** [comment]
No.

**Comment by zhuowei** [comment]
I am working on a new version; I won't get a chance to look into opening up this version until that's done.

**Comment by ZafotheNinja** [comment]
Awesome! Glad to hear this project isn't dead. Keep up the good work.

**Comment by Cavallium** [comment]
Please can you explain why you are interested in keeping secret the source code?
