### ISSUE TITLE
Error: java.util.zip.ZipException    |     Please help

### ISSUE THREAD

**Issue by RuudSchutten** [zhuowei/Boardwalk#331]
Version of Boardwalk: latest beta

Version of Android: 7.0

Device model: SM-T580

Description of the problem: https://afbeelding.im/DoZCzSTC
You can see the error in the image. Can you help me? Thnx!

"Error: Java.until.zip.ZipException

**Comment by hammy3502** [comment]
This is an error that occurs on every Nougat, Oreo, and Pie device. We'll just have to wait for a patch from zhuowei.
