### ISSUE TITLE
Another openjdk has been released

### ISSUE THREAD

**Issue by miguelmazetto** [zhuowei/Boardwalk#354]
I found a new openjdk when searching to already compiled versions of the original openjdk, and then i found the AdoptOpenJDK. Maybe now the boardwalk-2.0 project can go forward:
https://adoptopenjdk.net/releases.html
https://github.com/AdoptOpenJDK/openjdk8-binaries/releases
(in the case of the android for those who dont know,it would be the arm32 or aarch64 builds)
i will try this tomorrow :D

**Comment by Malaska678** [comment]
No android
