### ISSUE TITLE
Apk Of Boardwalk 2.0???

### ISSUE THREAD

**Issue by BryleHelll** [zhuowei/Boardwalk#369]
I want to test it @zhuowei .It is the original launcher of mc java for android. Bonus: Your not updating blocklaucher to 1.16.... I hope You Reed this :). Idea for boardwalk 3:
Forge 
Better performance
Mcpe controller
Recording

**Comment by BryleHelll** [comment]
@zhuowei

**Comment by fairerfnaf** [comment]
Es cierto ya publicalo

**Comment by BryleHelll** [comment]
Wat?

**Comment by BryleHelll** [comment]
English

**Comment by BryleHelll** [comment]
Pls

**Comment by BryleHelll** [comment]
@fairerfnaf

**Comment by BryleHelll** [comment]
Pls @zhuowei answer pls

**Comment by zhuowei** [comment]
@BryleHelll There are no plans to release a Boardwalk 2.0 at this time, since other launchers such as McInABox already have all those features.

Sorry about that.

**Comment by BryleHelll** [comment]
Sorrry because im to curious

**Comment by zhuowei** [comment]
@BryleHelll Again, I'm very sorry about this. (Also, while I currently am not working on BlockLauncher for 1.16.10 right now I do want to work on that when I have a chance to)

**Comment by fairerfnaf** [comment]
Ok yes im read your message and I wanted to ask you if you give me access
to boardwalk beta 2.0

**Comment by fairerfnaf** [comment]
Si pero por favor deme acceso :(
