### ISSUE TITLE
Boardwalk not launching Minecraft on the Nexus 9.

### ISSUE THREAD

**Issue by CrafterSheep** [zhuowei/Boardwalk#66]
Boardwalk Version: 1.0.7

Device Model: Nexus 9

Android Version: 5.0 Lollipop

Description: I try to launch Minecraft, and then it doesn't launch and gives me an error message instead

Screenshot of Error Message: ![screenshot_2014-12-01-21-23-00](https://cloud.githubusercontent.com/assets/10041033/5257228/2a8016dc-79a3-11e4-9c94-ee8870c5a611.png)

**Comment by zhuowei** [comment]
Can you please try the latest beta? http://zhuoweizhang.net/Boardwalk/Boardwalk-release.apk

**Comment by CrafterSheep** [comment]
Wow it works! Thank you!

**Comment by wasayk99** [comment]
Hey my boardwalk says that my account doesn't seems to minecraft user while I have logged in that accoint on mojang and minecraft website and my tablet is android but it don't have google services

**Comment by jbdman** [comment]
Stop hijacking other threads.

**Comment by jakey1995abc** [comment]
Still having same issue but on the oneplus two running android lollipop 5.1.1 oxygen OS (also 64bit)
