### ISSUE TITLE
why i can only play the demo?

### ISSUE THREAD

**Issue by Ferthekiller242** [zhuowei/Boardwalk#99]
Version of Boardwalk:1.0.6

Version of Android:5.0

Device model:google nexus 7

Description of the problem:i have minecraft PE no original but i have a account of mojan and i try to enter bit i can. Can u help me please?

**Comment by zhuowei** [comment]
You need to purchase the PC version of Minecraft.

**Comment by EnderBrine101** [comment]
You need the minecraft PC paid version fron minecraft.net
